### ISSUE TITLE
Операторы сравнения векторов

### ISSUE THREAD

**Issue by avasyukov** [turfe/linal#1]
Их можно или починить, или убрать (так-то их не было в требованиях).

Числа с плавающей точкой не стоит сравнивать на строгое равенство - оно не достигается примерно никогда. Нужно ввести какой-нибудь малый epsilon и сравнивать с ним модуль разности.

Хинт: после выписания этого в операторе равенства можно в операторе неравенства сказать просто ```return !(*this == v2);```.

**Comment by turfe** [comment]
Исправил операторы

**Comment by avasyukov** [comment]
Подтверждаю, решено.
